# deploy repo to cloud
name: Push to ECR
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust to your Node.js version

      - name: Install dependencies in the cloned repository
        working-directory: ./client
        run: npm install

      - name: Remove current env if it exists
        working-directory: ./client
        run: |
          if [ -f .env ]; then
            rm .env
          fi

      - name: Create .env file for client
        working-directory: ./client
        run:
          echo "VITE_API_PATH=''" > .env

      - name: Run npm build in the cloned repository
        working-directory: ./client
        run: npm run build  # Adjust to your build command
        env:
          CI : false

      - name: Copy index.html to server/templates/
        run: cp ./client/dist/index.html ./server/templates/
      
      - name: Replace assets directory in server
        run: |
          rm -rf ./server/assets
          cp -r ./client/dist/assets ./server/
        
      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > ./server/.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push the image to Amazon ECR
        working-directory: ./server
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rental-project
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"